#:import get_color_from_hex kivy.utils.get_color_from_hex

<LoginBtn@MDButton>:
    pos_hint: {"center_x": .5, "center_y": .5}

    on_release:
        app.load_screen(screen="main")

    MDButtonIcon:
        icon: "plus"

<MobileView>
    LoginBtn:
        MDButtonText:
            text: "Mobile main"

<TabletView>
    LoginBtn:
        MDButtonText:
            text: "Tablet main"
        MDButtonText:
            text: "Desktop main"

ResponsiveView:
    name: "login"