#:import get_color_from_hex kivy.utils.get_color_from_hex

<TestBtn@MDButton>:
    pos_hint: {"center_x": .5, "center_y": .5}

    on_release:
        app.load_screen(screen="login")

    MDButtonIcon:
        icon: "plus"

<MobileView>
    TestBtn:
        MDButtonText:
            text: "Mobile"

<TabletView>
    TestBtn:
        MDButtonText:
            text: "Tablet"

<DesktopView>
    TestBtn:
        MDButtonText:
            text: "Desktop"

ResponsiveView:
    name: "main"